// アプリ一覧。あとから足すときは、ここを直してフォルダを1つ足す。
const APPS = [
  {
    id: "flash-anzan",
    name: "フラッシュ暗算",
    search: "暗算・そろばん",
    desc: "数字がつぎつぎ出る。足し算。",
    href: "apps/flash-anzan/index.html",
    ready: true,
    thumb: "images/thumb-flash-anzan.jpg",
  },
  {
    id: "nanpure",
    name: "ナンプレ",
    search: "数独",
    desc: "せっていして、マスをうめる。",
    href: "apps/nanpure/index.html",
    ready: true,
    thumb: "images/thumb-nanpure.jpg",
  },
  {
    id: "crossword",
    name: "クロスワード",
    search: "ことばパズル",
    desc: "せっていして、ことばを入れる。",
    href: "apps/crossword/index.html",
    ready: true,
    thumb: "images/thumb-crossword.jpg",
  },
  {
    id: "prize-puzzle",
    name: "懸賞パズル",
    search: "イラストロジック",
    desc: "数字を見てマスを塗る。練習用。賞品はありません。",
    href: "apps/prize-puzzle/index.html",
    ready: true,
    thumb: "images/thumb-prize-puzzle.jpg",
  },
  {
    id: "easy-calc",
    name: "かんたん計算ゲーム",
    search: "計算",
    desc: "やさしい計算。せっていして、4つから選ぶ。",
    href: "apps/easy-calc/index.html",
    ready: true,
    thumb: "images/thumb-easy-calc.jpg",
  },
  {
    id: "gyakusho",
    name: "逆唱",
    search: "数字を逆から",
    desc: "設定して、出た数字を逆の順で答える。",
    href: "apps/gyakusho/index.html",
    ready: true,
    thumb: "images/thumb-gyakusho.jpg",
  },
  {
    id: "ato-janken",
    name: "後出しじゃんけん",
    search: "じゃんけん",
    desc: "相手のあとに、手を出す。せっていして遊ぶ。",
    href: "apps/ato-janken/index.html",
    ready: true,
    thumb: "images/thumb-ato-janken.jpg",
  },
];
