const SIZE = 5;
const BLACK = "#";
const LEVELS = ["やさしい", "ふつう", "むずかしい"];
const TIME_OPTS = [0, 180, 300, 600];

const PUZZLES = [
  {
    id: "harukaze-1",
    level: "やさしい",
    grid: ["はるかぜ#", "な###ね", "すし##こ", "##いぬ#", "やま###"],
    words: [
      {
        id: "a1",
        dir: "across",
        r: 0,
        c: 0,
        num: 1,
        answer: "はるかぜ",
        clue: "春にふく、やさしい風",
        hint: "季節の名前と、空をうごくものをつなげます",
        meaning: "春に吹く風",
      },
      {
        id: "d1",
        dir: "down",
        r: 0,
        c: 0,
        num: 1,
        answer: "はなす",
        clue: "口でことばを出すこと",
        hint: "「きく」の反対です",
        meaning: "口でことばを出すこと",
      },
      {
        id: "d2",
        dir: "down",
        r: 1,
        c: 4,
        num: 2,
        answer: "ねこ",
        clue: "にゃあとなく、小さな動物",
        hint: "あしが4本で、ねずみがすきです",
        meaning: "にゃあとなく小さな動物",
      },
      {
        id: "a3",
        dir: "across",
        r: 2,
        c: 0,
        num: 3,
        answer: "すし",
        clue: "しゃりにさかななどをのせる料理",
        hint: "おまつりやお弁当でもよく出ます",
        meaning: "しゃりにさかななどをのせる料理",
      },
      {
        id: "a4",
        dir: "across",
        r: 3,
        c: 2,
        num: 4,
        answer: "いぬ",
        clue: "わんとほえる、人の友だちにされる動物",
        hint: "さんぽがすきです",
        meaning: "わんとほえる、人の友だちになる動物",
      },
      {
        id: "a5",
        dir: "across",
        r: 4,
        c: 0,
        num: 5,
        answer: "やま",
        clue: "高くて、のぼるところ",
        hint: "ふもとからてっぺんまであるものです",
        meaning: "高くて、のぼるところ",
      },
    ],
  },
  {
    id: "tamago-1",
    level: "ふつう",
    grid: ["たまご#ね", "####こ", "みそしる#", "#####", "はな#いぬ"],
    words: [
      {
        id: "a1",
        dir: "across",
        r: 0,
        c: 0,
        num: 1,
        answer: "たまご",
        clue: "とりがうむ、白い食べ物",
        hint: "あさごはんにもよく出ます",
        meaning: "とりがうむ、白い食べ物",
      },
      {
        id: "d2",
        dir: "down",
        r: 0,
        c: 4,
        num: 2,
        answer: "ねこ",
        clue: "にゃあとなく、小さな動物",
        hint: "あしが4本で、ねずみがすきです",
        meaning: "にゃあとなく小さな動物",
      },
      {
        id: "a3",
        dir: "across",
        r: 2,
        c: 0,
        num: 3,
        answer: "みそしる",
        clue: "あさごはんによく出る、熱い汁",
        hint: "わかめやとうふを入れることもあります",
        meaning: "みそをといた熱い汁",
      },
      {
        id: "a4",
        dir: "across",
        r: 4,
        c: 0,
        num: 4,
        answer: "はな",
        clue: "いろがきれいで、においがするもの",
        hint: "はるにさく、さくらもこの仲間です",
        meaning: "いろやにおいを楽しむ植物",
      },
      {
        id: "a5",
        dir: "across",
        r: 4,
        c: 3,
        num: 5,
        answer: "いぬ",
        clue: "わんとほえる、人の友だちにされる動物",
        hint: "さんぽがすきです",
        meaning: "わんとほえる、人の友だちになる動物",
      },
    ],
  },
  {
    id: "sora-1",
    level: "むずかしい",
    grid: ["そら#つき", "う###り", "#はな##", "やま#かわ", "#####"],
    words: [
      {
        id: "a1",
        dir: "across",
        r: 0,
        c: 0,
        num: 1,
        answer: "そら",
        clue: "あたまのうえにひろがる、あおいところ",
        hint: "くもやとりがとぶ場所です",
        meaning: "あたまのうえにひろがる場所",
      },
      {
        id: "d1",
        dir: "down",
        r: 0,
        c: 0,
        num: 1,
        answer: "そう",
        clue: "「はい、そのとおり」と認めることば",
        hint: "相手の話に賛成するときに使います",
        meaning: "賛成するときの声",
      },
      {
        id: "a2",
        dir: "across",
        r: 0,
        c: 3,
        num: 2,
        answer: "つき",
        clue: "よるの空に出る、まるい星",
        hint: "地球のまわりを回っています",
        meaning: "よるの空に出る星",
      },
      {
        id: "d3",
        dir: "down",
        r: 0,
        c: 4,
        num: 3,
        answer: "きり",
        clue: "朝など、遠くが白くかすむ天気",
        hint: "山道で前が見えにくくなることがあります",
        meaning: "空気中の水で、遠くがかすむ天気",
      },
      {
        id: "a4",
        dir: "across",
        r: 2,
        c: 1,
        num: 4,
        answer: "はな",
        clue: "いろがきれいで、においがするもの",
        hint: "はるにさく、さくらもこの仲間です",
        meaning: "いろやにおいを楽しむ植物",
      },
      {
        id: "d4",
        dir: "down",
        r: 2,
        c: 1,
        num: 4,
        answer: "はま",
        clue: "海の水ぎわの、砂のところ",
        hint: "なみうちぎわです",
        meaning: "海の水ぎわ",
      },
      {
        id: "a5",
        dir: "across",
        r: 3,
        c: 0,
        num: 5,
        answer: "やま",
        clue: "高くて、のぼるところ",
        hint: "ふもとからてっぺんまであるものです",
        meaning: "高くて、のぼるところ",
      },
      {
        id: "a6",
        dir: "across",
        r: 3,
        c: 3,
        num: 6,
        answer: "かわ",
        clue: "水が流れて海へ行くところ",
        hint: "橋がかかっていることが多いです",
        meaning: "水が流れるところ",
      },
    ],
  },
];

let PUZZLE = PUZZLES[0];

// 難易度から問題を1つ選ぶ
function puzzleByLevel(level) {
  return PUZZLES.find((p) => p.level === level) || PUZZLES[0];
}

const KANA_COLS = [
  ["あ", "い", "う", "え", "お"],
  ["か", "き", "く", "け", "こ"],
  ["さ", "し", "す", "せ", "そ"],
  ["た", "ち", "つ", "て", "と"],
  ["な", "に", "ぬ", "ね", "の"],
  ["は", "ひ", "ふ", "へ", "ほ"],
  ["ま", "み", "む", "め", "も"],
  ["や", "ゆ", "よ"],
  ["ら", "り", "る", "れ", "ろ"],
  ["わ", "を", "ん"],
];

const DAKU = {
  か: "が",
  き: "ぎ",
  く: "ぐ",
  け: "げ",
  こ: "ご",
  さ: "ざ",
  し: "じ",
  す: "ず",
  せ: "ぜ",
  そ: "ぞ",
  た: "だ",
  ち: "ぢ",
  つ: "づ",
  て: "で",
  と: "ど",
  は: "ば",
  ひ: "び",
  ふ: "ぶ",
  へ: "べ",
  ほ: "ぼ",
};

const HANDAKU = { は: "ぱ", ひ: "ぴ", ふ: "ぷ", へ: "ぺ", ほ: "ぽ" };
const DAKU_BACK = Object.fromEntries(
  Object.entries(DAKU).map(([a, b]) => [b, a])
);
const HANDAKU_BACK = Object.fromEntries(
  Object.entries(HANDAKU).map(([a, b]) => [b, a])
);
